on: [push, pull_request]

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            fetch-tags: true
        - name: Set up Zig
          uses: goto-bus-stop/setup-zig@v2
          with:
            version: '0.12.1'
        - name: Lint
          run: ./tools/fmt-check.sh
        - name: Test
          run: zig build test
        - name: Build SDL2
          run: |
            sudo apt-get install -y libsdl2-dev
            zig build -Ddriver=sdl2
        - name: Build X11
          run: zig build -Ddriver=x11
        - name: Build Aarch64
          run: |
            zig build -Ddriver=fbev -Dtarget=aarch64-linux-musl -Doptimize=ReleaseSafe -Dstrip
            sha256sum zig-out/bin/nd zig-out/bin/ngui
        - name: Playground
          run: zig build guiplay btcrpc lndhc
